sudo: required
services:
    - docker

before_install:
    - docker build -t jkw5/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jkw5/react-test npm test

after_success:
    - docker build -t jkw5/multi-client ./client
    - docker build -t jkw5/multi-nginx ./nginx
    - docker build -t jkw5/multi-server ./server
    - docker build -t jkw5/multi-worker ./worker

    # login to docker CLI
    - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD docker.io

    # take images and push them to dockerhub
    - docker push jkw5/multi-client
    - docker push jkw5/multi-nginx
    - docker push jkw5/multi-server
    - docker push jkw5/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: eu-central-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-central-1-997189782442
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY